// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         jobId: "jobId"
 *     }
 */
export interface CancelJobRequest {
    /** Identifier returned from an async job submission (e.g., `/extract_async`). */
    jobId: string;
}
