// This file was auto-generated by Fern from our API Definition.

import type * as Pulse from "../../../../index.js";

/**
 * @example
 *     {
 *         steps: {}
 *     }
 */
export interface PipelineExecuteInput {
    /** URL of the document to process. Use with `extract` step. */
    file_url?: string;
    /** Ordered step definitions. Key order determines execution order. */
    steps: Pulse.PipelineSteps;
    /** If true, returns immediately with a `job_id` for polling via `GET /job/{jobId}`. */
    async?: boolean;
    /** If true, all stored artifacts are deleted immediately after you receive the results. The inline data in the response is unaffected. Requires `save_extractions` to be disabled for your organization. */
    auto_delete?: boolean;
}
