// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../../../../core/index.js";

/**
 * @example
 *     {}
 */
export interface FormDetectMultipartInput {
    /** Direct binary upload of the PDF. Mutually exclusive with `file_url` and `form_id`. */
    file?: core.file.Uploadable | undefined;
    /** Public or pre-signed URL of a PDF Pulse will download. Mutually exclusive with `file` and `form_id`. */
    file_url?: string;
    /** Reference to a previously processed form. Mutually exclusive with `file` / `file_url`. */
    form_id?: string;
    /** Restrict the operation to a subset of pages, e.g. `"1-3,5"`. */
    page_range?: string;
    /** Set to `"true"` to run asynchronously and receive `{job_id, status}` immediately. */
    async?: string;
}
