// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         jobId: "jobId"
 *     }
 */
export interface GetLargeResultLargeResultsRequest {
    /** Job identifier from the extraction response. */
    jobId: string;
}
