// This file was auto-generated by Fern from our API Definition.

/**
 * Acknowledgement returned when a request is submitted for asynchronous processing. Poll `GET /job/{job_id}` to check status and retrieve results.
 */
export interface AsyncSubmissionResponse {
    /** Identifier assigned to the asynchronous job. */
    job_id: string;
    /** Initial status reported by the server. */
    status: AsyncSubmissionResponse.Status;
    /** Human-readable description of the accepted job. */
    message?: string;
    /** **Deprecated** — Timestamp indicating when the job was accepted. Retained for backward compatibility. Use `GET /job/{jobId}` for timing details. */
    queuedAt?: string;
    /** Number of credits consumed by this request. Only present when the organization has the credit billing system enabled. */
    credits_used?: number | null;
}

export namespace AsyncSubmissionResponse {
    /** Initial status reported by the server. */
    export const Status = {
        Pending: "pending",
        Processing: "processing",
        Completed: "completed",
        Failed: "failed",
        Canceled: "canceled",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
