// This file was auto-generated by Fern from our API Definition.

/**
 * Acknowledgement returned when batch schema is started.
 */
export interface BatchSchemaResponse {
    /** Identifier for the batch job. Poll `GET /job/{batch_job_id}` for progress and results. */
    batch_job_id: string;
    status: BatchSchemaResponse.Status;
    /** Number of extractions to process (single mode). */
    total_extractions?: number;
    /** Number of splits to process (split mode). */
    total_splits?: number;
}

export namespace BatchSchemaResponse {
    export const Status = {
        Processing: "processing",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
