// This file was auto-generated by Fern from our API Definition.

export interface BatchFileUpload {
    /** Original filename including extension (e.g. `report.pdf`). */
    filename: string;
    /** Base64-encoded file content. */
    content: string;
}
