// This file was auto-generated by Fern from our API Definition.

/**
 * Identifies extractions for batch processing.
 * Provide exactly one of `batch_extract_id` or `extraction_ids`.
 */
export interface BatchExtractionIds {
    /** ID of a prior `/batch/extract` run. All completed child extraction IDs will be used. */
    batch_extract_id?: string;
    /** Explicit list of extraction IDs to process. */
    extraction_ids?: string[];
}
