// This file was auto-generated by Fern from our API Definition.

/**
 * Output destination for batch results. Provide at least one of
 * `s3_prefix` or `local_path`. Both may be specified to save to
 * multiple locations.
 */
export interface BatchOutputDestination {
    /** S3 URI prefix where result JSON files will be written. */
    s3_prefix?: string;
    /** Absolute path to a local directory for result JSON files. */
    local_path?: string;
}
