// This file was auto-generated by Fern from our API Definition.

/**
 * Acknowledgement returned when batch split is started.
 */
export interface BatchSplitResponse {
    /** Identifier for the batch job. Poll `GET /job/{batch_job_id}` for progress and results. */
    batch_job_id: string;
    status: BatchSplitResponse.Status;
    /** Number of extractions to process. */
    total_extractions: number;
}

export namespace BatchSplitResponse {
    export const Status = {
        Processing: "processing",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
