// This file was auto-generated by Fern from our API Definition.

/**
 * Acknowledgement returned when a batch extraction is started.
 */
export interface BatchExtractResponse {
    /** Identifier for the batch job. Poll `GET /job/{batch_job_id}` for progress and results. */
    batch_job_id: string;
    status: BatchExtractResponse.Status;
    /** Number of files that will be processed. */
    total_files: number;
}

export namespace BatchExtractResponse {
    export const Status = {
        Processing: "processing",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
