// This file was auto-generated by Fern from our API Definition.

import type * as Pulse from "../index.js";

/**
 * Input source for batch file enumeration. Provide exactly one of
 * `s3_prefix`, `file_urls`, or `files`.
 */
export interface BatchInputSource {
    /** S3 URI prefix (e.g. `s3://bucket/folder/`). All supported files under this prefix will be processed. */
    s3_prefix?: string;
    /** Explicit list of file URLs to download and process. */
    file_urls?: string[];
    /** Inline file uploads. Each entry contains a filename and base64-encoded file content. Use this when the client has local files that need to be sent to a remote API server. */
    files?: Pulse.BatchFileUpload[];
}
