// This file was auto-generated by Fern from our API Definition.

/**
 * Input source for batch file enumeration. Provide exactly one of
 * `s3_prefix`, `local_path`, or `file_urls`.
 */
export interface BatchInputSource {
    /** S3 URI prefix (e.g. `s3://bucket/folder/`). All supported files under this prefix will be processed. */
    s3_prefix?: string;
    /** Absolute path to a local directory. All supported files in the directory will be processed. */
    local_path?: string;
    /** Explicit list of file URLs to download and process. */
    file_urls?: string[];
}
