// This file was auto-generated by Fern from our API Definition.

/**
 * Common base shape used for `Text`, `Title`, and `Footer` bounding-box entries. Spreadsheet rows may carry additional sheet-scoped fields such as `excel_range` and `sheet_name`; forward-compatible extra properties are accepted.
 */
export interface BoundingBoxItem {
    /** Stable bounding-box identifier (e.g. `txt-1`, `excel_title_0`). Used by extensions like `footnoteReferences` to cross-reference paragraphs. */
    id?: string;
    /** Plain-text content of the region. */
    content?: string;
    /** 1-indexed page number. For spreadsheets this matches the parsed sheet index after hidden-sheet filtering. */
    page_number?: number;
    /** Document coordinate polygon when available. Spreadsheet visuals may use an empty array and `excel_range` instead. */
    bounding_box?: number[];
    /** Spreadsheet-only anchor or covered cell range. */
    excel_range?: string;
    /** Spreadsheet-only sheet name. */
    sheet_name?: string;
    /** Spreadsheet-only parsed sheet index after hidden-sheet filtering. */
    sheet_index?: number;
    /** Spreadsheet-only original workbook sheet index. */
    workbook_sheet_index?: number;
    /** Accepts any additional properties */
    [key: string]: any;
}
