// This file was auto-generated by Fern from our API Definition.

import type * as Pulse from "../index.js";

/**
 * Detected or embedded visual (chart or image) returned under `bounding_boxes.Images`. For PDFs/images, populated when figure detection is enabled. For spreadsheets, populated for embedded charts and images. `image_url` is set when `figure_processing.show_images` is enabled.
 */
export interface BoundingBoxImage {
    /** Stable visual identifier (e.g. `excel_image_1_1`, `fig-3`). Use this to join with the `data-bb-image-id` attribute in the markdown output. */
    id: string;
    /** Short caption for the visual (e.g. `Chart: Revenue`). Populated by the spreadsheet parser; PDF figures may leave this empty when no caption is detected. */
    content?: string;
    /** Visual class. Drives whether `figure_processing.description` / `figure_processing.show_images` apply to this entry. */
    visual_type: Pulse.VisualType;
    /** 1-indexed page or sheet index. */
    page_number?: number;
    /** Document coordinate polygon when available. Spreadsheet visuals typically use an empty array and rely on `excel_range` for positioning. */
    bounding_box?: number[];
    /** Pulse-hosted URL for the visual image bytes. Present when `figure_processing.show_images` was enabled for this visual_type. Spreadsheet visuals proxy through `GET /results/{jobId}/images/{filename}`; inline figure flows may use a data URI. */
    image_url?: string;
    /** Generated visual description. Present when `figure_processing.description` was enabled for this visual_type. */
    description?: string;
    /** Visual classification metadata when classification was run. Includes confidence, model name, and any non-fatal classification error. */
    classification?: BoundingBoxImage.Classification;
    /** Spreadsheet-only sheet name. */
    sheet_name?: string;
    /** Spreadsheet-only parsed sheet index after hidden-sheet filtering. */
    sheet_index?: number;
    /** Spreadsheet-only original workbook sheet index. */
    workbook_sheet_index?: number;
    /** Spreadsheet-only anchor or covered cell range for the visual. */
    excel_range?: string;
    /** Spreadsheet chart class name (e.g. `BarChart`, `LineChart`) when `visual_type` is `chart`. */
    chart_type?: string;
    /** Spreadsheet chart title when available. */
    chart_title?: string;
    /** Spreadsheet chart source ranges when available, e.g. `["Charts!$B$1:$B$3"]`. */
    source_ranges?: string[];
    /** Optional non-fatal rendering error for spreadsheet visuals. When set, the visual entry is still returned but `image_url` may be omitted. */
    render_error?: string;
    /** Optional non-fatal description-generation error. */
    description_error?: string;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace BoundingBoxImage {
    /**
     * Visual classification metadata when classification was run. Includes confidence, model name, and any non-fatal classification error.
     */
    export interface Classification {
        confidence?: number;
        model?: string;
        error?: string;
        /** Accepts any additional properties */
        [key: string]: any;
    }
}
