// This file was auto-generated by Fern from our API Definition.

import type * as Pulse from "../index.js";

/**
 * Positional bounding-box data for text, titles, headers, footers, images, and tables. Used by the frontend for annotation overlays and by SDK consumers to access detected visuals (charts and images) returned under `Images`. Keys not listed here are accepted for forward compatibility (e.g. `markdown_with_ids`, `defined_names`).
 */
export interface BoundingBoxes {
    /** Detected or embedded visuals. `image_url` is populated when `figure_processing.show_images` was enabled and the entry's `visual_type` matched the requested target. */
    Images?: Pulse.BoundingBoxImage[];
    /** Detected tables. Each entry carries a `table_info` block plus optional `cell_data`. */
    Tables?: Pulse.BoundingBoxTable[];
    /** Body-text paragraphs and detected text regions. For spreadsheets, includes free-form text outside table regions (titles, captions, instructions). */
    Text?: Pulse.BoundingBoxItem[];
    /** Detected title regions. Spreadsheets emit one `Sheet: <name>` title per processed sheet. */
    Title?: Pulse.BoundingBoxItem[];
    /** Detected footer regions (e.g. spreadsheet "Totals" rows, PDF page footers). */
    Footer?: Pulse.BoundingBoxItem[];
    /** Markdown variant with stable `data-bb-*-id` attributes in figure / table / text tags. Lets clients join rendered HTML back to bounding-box entries by id. */
    markdown_with_ids?: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
