// This file was auto-generated by Fern from our API Definition.

/**
 * Detected table region returned under `bounding_boxes.Tables`. Carries a structured `table_info` block plus optional `cell_data`. Kept loose with `additionalProperties: true` to round-trip future fields the server may add (e.g. layout metadata).
 */
export interface BoundingBoxTable {
    table_info?: BoundingBoxTable.TableInfo;
    /** Table cell payload when available. Shape varies by extraction path; SDK consumers should treat as opaque. */
    cell_data?: Record<string, unknown>[];
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace BoundingBoxTable {
    export interface TableInfo {
        id?: string;
        dimensions?: number[];
        excel_range?: string;
        sheet_name?: string;
        sheet_index?: number;
        workbook_sheet_index?: number;
        section_index?: number;
        section_type?: string;
        section_name?: string;
        table_name?: string;
        layout_type?: string;
        is_chart?: boolean;
        chart_type?: string;
        chart_title?: string;
        source_ranges?: string[];
        location?: Record<string, unknown>;
        /** Accepts any additional properties */
        [key: string]: any;
    }
}
