// This file was auto-generated by Fern from our API Definition.

import type * as Pulse from "../index.js";

/**
 * Full extraction result returned by the synchronous `/extract` endpoint. Contains the extracted markdown (or HTML), optional structured data, chunked content, bounding boxes, and storage metadata.
 */
export interface ExtractResponse {
    /** Primary markdown content extracted from the document. Present when `returnHtml` is false or omitted. */
    markdown?: string;
    /** HTML representation of the extracted content. Present when `returnHtml` is true. */
    html?: string;
    /** Structured data extracted using the provided schema. Only present when a schema was included in the request (via `structuredOutput` or legacy `schema` field). */
    structured_output?: Pulse.StructuredOutputResult;
    /** Document content split into chunks using the requested strategies. Only present when `chunking` was specified in the request. */
    chunks?: ExtractResponse.Chunks;
    /** Positional bounding-box data for text, titles, headers, footers, images, and tables. Used by the frontend for annotation overlays. */
    bounding_boxes?: Record<string, unknown>;
    /** Persisted extraction ID. Present when storage is enabled (default). Use this ID with `/split` and `/schema` endpoints. */
    extraction_id?: string;
    /** URL to view the extraction on the Pulse platform. Present when storage is enabled. */
    extraction_url?: string;
    /** Number of pages processed. */
    page_count?: number;
    /** Echo of the schema that was applied. Present when a schema was included in the request. */
    input_schema?: Record<string, unknown>;
    /** Billing tier and usage information. */
    "plan-info"?: ExtractResponse.PlanInfo;
    /** Error message if schema processing failed. The extraction still succeeds but structured data may be missing. */
    schema_error?: string;
    /** Time spent on schema processing, in seconds. */
    schema_processing_time_seconds?: number;
    /** **Deprecated** — Alias for `markdown`. Included for backward compatibility with older SDK versions. Prefer `markdown`. */
    content?: string;
    /** **Deprecated** — Identifier assigned to the extraction job. Retained for backward compatibility. */
    job_id?: string;
    /** **Deprecated** — Non-fatal warnings generated during extraction. Retained for backward compatibility. */
    warnings?: string[];
    /** **Deprecated** — Additional metadata supplied by the backend. Retained for backward compatibility. */
    metadata?: Record<string, unknown>;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace ExtractResponse {
    /**
     * Document content split into chunks using the requested strategies. Only present when `chunking` was specified in the request.
     */
    export interface Chunks {
        /** Semantically-segmented chunks. */
        semantic?: string[];
        /** Chunks split by document headers/headings. */
        header?: string[];
        /** One chunk per page. */
        page?: string[];
        /** Recursively-split chunks respecting size limits. */
        recursive?: string[];
    }

    /**
     * Billing tier and usage information.
     */
    export interface PlanInfo {
        /** Current plan tier name. */
        tier?: string;
        /** Cumulative pages used after this extraction. */
        pages_used?: number;
        /** Human-readable plan note. */
        note?: string;
    }
}
