// This file was auto-generated by Fern from our API Definition.

/**
 * Metadata describing the enqueued asynchronous extraction job.
 */
export interface ExtractAsyncResponse {
    /** Identifier assigned to the asynchronous extraction job. */
    job_id: string;
    /** Initial status reported by the extractor. */
    status: ExtractAsyncResponse.Status;
    /** Timestamp indicating when the job was accepted. */
    queuedAt?: string;
}

export namespace ExtractAsyncResponse {
    /** Initial status reported by the extractor. */
    export const Status = {
        Pending: "pending",
        Processing: "processing",
        Completed: "completed",
        Failed: "failed",
        Canceled: "canceled",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
