// This file was auto-generated by Fern from our API Definition.

/**
 * High-level structure returned by the synchronous extract API.
 */
export interface ExtractResponse {
    /** Primary markdown content extracted from the document. */
    content?: string;
    /** Optional HTML representation when returnHtml is true. */
    html?: string;
    /** Identifier assigned to the extraction job. */
    job_id?: string;
    /** Non-fatal warnings generated during extraction. */
    warnings?: string[];
    /** Additional metadata supplied by the backend. */
    metadata?: Record<string, unknown>;
    /** Accepts any additional properties */
    [key: string]: any;
}
