// This file was auto-generated by Fern from our API Definition.

import type * as Pulse from "../index.js";

/**
 * Returned instead of the full extraction result when the document has 70 or more pages.  The `url` field is a single-use download link; fetch it once to retrieve the complete `ExtractResultCore` payload. Subsequent requests to the same URL return 410 Gone.
 */
export interface ExtractLargeResultResponse {
    /** Always `true` for large document responses. */
    is_url: boolean;
    /** Single-use URL to download the full extraction result.  After one successful download the resource is deleted and further requests return 410 Gone. */
    url: string;
    /** Extraction identifier (when storage is enabled). */
    extraction_id?: string;
    /** Number of pages in the document. */
    page_count?: number;
    /** Billing tier and cumulative usage information. Includes `total_credits_used` (primary billing metric) and `pages_used` (legacy compatibility). */
    plan_info?: Pulse.PlanInfo;
}
