// This file was auto-generated by Fern from our API Definition.

import type * as Pulse from "../index.js";

/**
 * **Deprecated** — Use `AsyncSubmissionResponse` instead. This alias is retained so that existing SDK imports continue to work.
 */
export type ExtractAsyncSubmissionResponse = Pulse.AsyncSubmissionResponse;
