// This file was auto-generated by Fern from our API Definition.

import type * as Pulse from "../index.js";

/**
 * Result body returned by `/form/detect`, `/form/fill`, and
 * `/form/clear`. For async jobs (`async: true`) the same shape is
 * served back under `result` on
 * [GET /job/{jobId}](api:GET/job/{jobId}).
 */
export interface FormResult {
    /** ID of the form record produced by this run. Pass to a subsequent `/form/detect`, `/form/fill`, or `/form/clear` call as the single input source to iterate without re-uploading the PDF. */
    form_id?: string;
    /** Number of pages in the output PDF. */
    page_count?: number;
    /** URL to download the resulting PDF binary. Always points at [GET /results/{jobId}/pdf](api:GET/results/{jobId}/pdf) for the originating job. Authenticated callers can replay this URL until the underlying artifact is garbage-collected. */
    pdf_url?: string;
    /** Detected cells of the resulting PDF (refreshed from the filled/cleared output for fill/clear, or freshly detected for `/form/detect`). Use these as a starting point for further edits. */
    form_fields?: Pulse.FormCell[];
    /** Number of cells that were filled by this run. Present on `/form/fill` responses only. */
    fields_filled?: number;
    /** Number of cells that were cleared by this run. Present on `/form/clear` responses only. */
    fields_cleared?: number;
    /** Number of credits consumed by **this request**. Detect charges 1 credit per page; fill and clear charge 3 credits per page. */
    credits_used?: number;
    /** Billing tier and cumulative usage information for the calling org, including this form run. */
    plan_info?: Pulse.PlanInfo;
}
