// This file was auto-generated by Fern from our API Definition.

/**
 * Optional knobs accepted by `/form/detect`, `/form/fill`, and `/form/clear` regardless of input mode.
 */
export interface FormSharedOptions {
    /** Restrict the operation to a subset of pages. Accepts comma-separated page numbers and ranges, e.g. `"1-3,5"`. Alias: `pages`. */
    page_range?: string;
    /** When `true`, the endpoint returns immediately with `{job_id, status: "pending"}` (HTTP 202) and processes the job in the background. Poll [GET /job/{jobId}](api:GET/job/{jobId}) for the result. Default `false` — return the full result inline. */
    async?: boolean;
}
