// This file was auto-generated by Fern from our API Definition.

import type * as Pulse from "../index.js";

/**
 * A single detected cell on a form page. Cells are produced by Pulse
 * cell detection during a `/form/detect`, `/form/fill`, or
 * `/form/clear` call and may be passed back via `form_fields` to
 * override what Pulse uses when filling or clearing.
 *
 * All coordinate fields (`bounding_box`, `checkbox_coord`) are
 * normalized to `[0, 1]` relative to the page width / height, so
 * they're independent of the renderer's pixel resolution. Multiply
 * by your render width / height to convert to your own pixel space.
 * `page_number` is 1-indexed.
 */
export interface FormCell {
    /** 1-indexed page the cell belongs to. */
    page_number?: number;
    /** Cell bounding box `[x1, y1, x2, y2]` normalized to the range `[0, 1]` (top-left origin). Same shape as the `bounding_box` field returned by `/extract`. */
    bounding_box?: number[];
    /** Current text content of the cell. Empty string for unfilled cells. */
    text?: string;
    /** Detected cell type. Common values are `text`, `checkbox`, and `signature`. Additional values may be returned as the detector evolves. */
    type?: FormCell.Type;
    /** Row index inside the detected table this cell belongs to, when the cell sits in a tabular region. */
    row?: number;
    /** Column index inside the detected table this cell belongs to, when the cell sits in a tabular region. */
    col?: number;
    /** Index of the detected table on the page this cell belongs to (0-indexed). Cells outside any detected table may omit this field. */
    table_idx?: number;
    /** Only present when `type == "checkbox"`. One entry per individual checkbox inside this cell — a single cell often contains multiple checkboxes (e.g. a "Filing Status" row with Single / MFJ / MFS / HoH / QSS). The cell-level `text` is the raw OCR'd line covering the whole cell; per-box labels live here on each detail. */
    checkbox_details?: Pulse.FormCheckboxDetail[];
}

export namespace FormCell {
    /** Detected cell type. Common values are `text`, `checkbox`, and `signature`. Additional values may be returned as the detector evolves. */
    export const Type = {
        Text: "text",
        Checkbox: "checkbox",
        Signature: "signature",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
}
