// This file was auto-generated by Fern from our API Definition.

/**
 * A single checkbox inside a `FormCell` of `type == "checkbox"`. Bundles the checkbox's normalized center coordinate, current selection state, and the per-box text label.
 */
export interface FormCheckboxDetail {
    /** Normalized `[x, y]` center of the checkbox (in `[0, 1]`, top-left origin), in the same coordinate system as `FormCell.bounding_box`. */
    center_coord?: number[];
    /** `true` when the checkbox is currently filled in (selected), `false` otherwise. */
    selected?: boolean;
    /** Per-checkbox text label (e.g. `"Individual/sole proprietor"`, `"S corporation"`). May be an empty string when no label could be confidently associated with this specific box. */
    text?: string;
}
