// This file was auto-generated by Fern from our API Definition.

/**
 * Cumulative billing snapshot for the calling organization. Sourced from the `pulse-org-stats` aggregate table maintained asynchronously by the org-stats Lambda; the in-flight request's contribution is added on top so every response reflects post-request state.
 */
export interface FormPlanInfo {
    /** Billing tier, e.g. `"trial"`, `"pulse_ultra_2"`. */
    tier?: string;
    /** Total credits consumed by the organization to date, including this request. The primary billing metric going forward. */
    total_credits_used?: number;
    /** Total pages processed by the organization to date, including this request. Kept for backward compatibility with clients that haven't migrated to `total_credits_used`. */
    pages_used?: number;
}
