// This file was auto-generated by Fern from our API Definition.

/**
 * Multipart `/form/detect` request. Use this variant to upload a
 * PDF directly via `file`.
 */
export interface FormDetectMultipartInput {
    /** PDF file to upload directly. */
    file?: string;
    /** Alternative to `file`: a public or pre-signed URL Pulse will download. */
    file_url?: string;
    /** Reference to a previously processed form. Mutually exclusive with `file` / `file_url`. */
    form_id?: string;
    /** Restrict the operation to a subset of pages, e.g. `"1-3,5"`. */
    page_range?: string;
    /** Set to `"true"` to run asynchronously and receive `{job_id, status}` immediately. */
    async?: string;
}
