// This file was auto-generated by Fern from our API Definition.

import type * as Pulse from "../index.js";

/**
 * **Deprecated** — Use `PlanInfo` instead. Retained as an alias so existing SDK type imports continue to compile.
 */
export type FormPlanInfo = Pulse.PlanInfo;
