// This file was auto-generated by Fern from our API Definition.

/**
 * Multipart `/form/fill` request. Use this variant to upload a
 * PDF directly via `file`. Provide exactly one of `file`,
 * `file_url`, or `form_id`.
 */
export interface FormFillMultipartInput {
    /** PDF file to upload directly. */
    file?: string;
    /** Alternative to `file`: a public or pre-signed URL Pulse will download. */
    file_url?: string;
    /** Reference to a previously processed form. Mutually exclusive with `file` / `file_url`. */
    form_id?: string;
    /** Required natural-language fill prompt. */
    instructions?: string;
    /** Optional JSON-encoded array of `FormCell` objects to override detected cells. Multipart bodies must serialise this field as a string. */
    form_fields?: string;
    /** Restrict the operation to a subset of pages, e.g. `"1-3,5"`. */
    page_range?: string;
    /** Set to `"true"` to run asynchronously and receive `{job_id, status}` immediately. */
    async?: string;
}
