// This file was auto-generated by Fern from our API Definition.

import type * as Pulse from "../index.js";

/**
 * Cell-level overrides accepted by `/form/fill` and `/form/clear`.
 */
export interface FormFillSharedOptions {
    /** Optional override for the cells used when filling / clearing. When omitted, Pulse uses the cells stored on the referenced `form_id` (fast path) or runs detection on the uploaded PDF. Useful for editing detected cells before filling. */
    form_fields?: Pulse.FormCell[];
    /** Restrict the operation to a subset of pages. Accepts comma-separated page numbers and ranges, e.g. `"1-3,5"`. Alias: `pages`. */
    page_range?: string;
    /** When `true`, the endpoint returns immediately with `{job_id, status: "pending"}` (HTTP 202) and processes the job in the background. Poll [GET /job/{jobId}](api:GET/job/{jobId}) for the result. Default `false` — return the full result inline. */
    async?: boolean;
}
