// This file was auto-generated by Fern from our API Definition.

/**
 * JSON request body for `/form/detect`. Provide exactly one of
 * `form_id`, `file_url`, or `file` (multipart only).
 */
export interface FormDetectJsonInput {
    /** Re-detect cells on a previously stored PDF (returned by an earlier `/form/detect`, `/form/fill`, or `/form/clear` call). Useful when chaining detect calls or refreshing layout after edits. */
    form_id?: string;
    /** Public or pre-signed URL of a PDF to detect cells on. */
    file_url?: string;
    /** Restrict the operation to a subset of pages. Accepts comma-separated page numbers and ranges, e.g. `"1-3,5"`. Alias: `pages`. */
    page_range?: string;
    /** When `true`, the endpoint returns immediately with `{job_id, status: "pending"}` (HTTP 202) and processes the job in the background. Poll [GET /job/{jobId}](api:GET/job/{jobId}) for the result. Default `false` — return the full result inline. */
    async?: boolean;
}
