// This file was auto-generated by Fern from our API Definition.

export interface GoneErrorBody {
    error?: GoneErrorBody.Error_;
}

export namespace GoneErrorBody {
    export interface Error_ {
        code?: string;
        message?: string;
    }
}
