// This file was auto-generated by Fern from our API Definition.

/**
 * Confirmation payload returned after successfully canceling a job.
 */
export interface JobCancellationResponse {
    /** Identifier of the job that was cancelled. */
    job_id: string;
    /** Human-readable confirmation message. */
    message: string;
}
