// This file was auto-generated by Fern from our API Definition.

import type * as Pulse from "../index.js";

/**
 * Current status and metadata for an asynchronous extraction job.
 */
export interface JobStatusResponse {
    /** Identifier assigned to the asynchronous extraction job. */
    job_id: string;
    status: Pulse.JobStatus;
    /** Timestamp when the job was accepted. */
    created_at: string;
    /** Timestamp of the last status update, if available. */
    updated_at?: string;
    /** Structured payload that contains extraction output when the job is completed. */
    result?: Record<string, unknown>;
    /** Error message describing why the job failed, if applicable. */
    error?: string;
}
