// This file was auto-generated by Fern from our API Definition.

import type * as Pulse from "../index.js";

/**
 * Current status and metadata for an asynchronous job.
 */
export interface JobStatusResponse {
    /** Identifier assigned to the asynchronous job. */
    job_id: string;
    status: Pulse.JobStatus;
    /** Timestamp when the job was accepted. */
    created_at: string;
    /** Timestamp of the last status update, if available. */
    updated_at?: string;
    /** Structured payload returned when the job completes.  For large extractions (70+ pages) this object contains `is_url: true` and a single-use `url` to download the full result via `GET /large_results/{jobId}`. */
    result?: Record<string, unknown>;
    /** Error message describing why the job failed, if applicable. */
    error?: string;
}
