// This file was auto-generated by Fern from our API Definition.

/** Lifecycle status for an asynchronous extraction job. */
export const JobStatus = {
    Pending: "pending",
    Processing: "processing",
    Completed: "completed",
    Failed: "failed",
    Canceled: "canceled",
} as const;
export type JobStatus = (typeof JobStatus)[keyof typeof JobStatus];
