// This file was auto-generated by Fern from our API Definition.

/**
 * Document source definition for JSON requests.
 */
export interface JsonSource {
    /** Public or pre-signed URL that Pulse will download and extract. */
    fileUrl: string;
}
