// This file was auto-generated by Fern from our API Definition.

/**
 * Document source definition for multipart/form-data requests.
 */
export interface MultipartSource {
    /** Document to upload directly. Required unless fileUrl is specified. */
    file: string;
    /** Public or pre-signed URL that Pulse will download and extract. */
    fileUrl?: string;
}
