// This file was auto-generated by Fern from our API Definition.

/**
 * Document source definition for multipart/form-data requests. Provide exactly one of `file` (direct upload) or `fileUrl` (remote URL).
 */
export type MultipartSource =
    | {
          file: string;
          fileUrl?: unknown | undefined;
      }
    | {
          fileUrl: string;
          file?: unknown | undefined;
      };
