// This file was auto-generated by Fern from our API Definition.

/**
 * Document source definition for multipart/form-data requests. Provide exactly one of `file` (direct upload) or `fileUrl` (remote URL).
 */
export interface MultipartSource {
    /** Document to upload directly. Required unless fileUrl is provided. */
    file?: string;
    /** Public or pre-signed URL that Pulse will download and extract. Required unless file is provided. */
    fileUrl?: string;
}
