// This file was auto-generated by Fern from our API Definition.

import type * as Pulse from "../index.js";

/**
 * Result from the split step in a pipeline. Inherits all core split fields and adds pipeline-specific timing and input echo.
 */
export interface PipelineSplitResult {
    /** Unique identifier for this split result. Use this ID with the `/schema` endpoint (split mode) to apply schemas to specific page groups. */
    split_id?: string;
    /** Page assignments per topic. */
    split_output?: Pulse.SplitOutput;
    /** Number of credits consumed by this request. Only present when the organization has the credit billing system enabled. */
    credits_used?: number | null;
    /** Billing tier and cumulative usage information for the calling org, including this split run. */
    plan_info?: Pulse.PlanInfo;
    /** Echo of the topic definitions used. */
    split_input?: Pulse.TopicDefinition[];
    /** Step execution time in seconds. */
    latency?: number;
    /** Accepts any additional properties */
    [key: string]: any;
}
