// This file was auto-generated by Fern from our API Definition.

/**
 * Result from the tables step in a pipeline.
 */
export interface PipelineTablesResult {
    /** Persisted tables version ID. */
    tables_id?: string;
    /** The extracted tables data. */
    tables_output?: PipelineTablesResult.TablesOutput;
    /** Step execution time in seconds. */
    latency?: number;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace PipelineTablesResult {
    /**
     * The extracted tables data.
     */
    export interface TablesOutput {
        /** Array of extracted table objects. Each table includes its content, citations, and whether it was derived from a chart. */
        tables?: TablesOutput.Tables.Item[];
    }

    export namespace TablesOutput {
        export type Tables = Tables.Item[];

        export namespace Tables {
            export interface Item {
                /** The table content. When `table_format` is `html` (default), this is an HTML string. When `json`, this is an object with `headers` and `rows`. */
                table_content?: unknown;
                citations?: string[];
                from_chart?: boolean;
            }
        }
    }
}
