// This file was auto-generated by Fern from our API Definition.

import type * as Pulse from "../index.js";

/**
 * Results from each pipeline step, keyed by step name. Only steps that were executed are present.
 */
export interface PipelineResults {
    /** Extract step result. */
    extract?: Pulse.PipelineExtractResult;
    /** Batch extract step result. */
    batch_extract?: Pulse.PipelineBatchExtractResult;
    /** Schema step result. */
    schema?: Pulse.PipelineSchemaResult;
    /** Split step result. */
    split?: Pulse.PipelineSplitResult;
    /** Tables step result. */
    tables?: Pulse.PipelineTablesResult;
}
