// This file was auto-generated by Fern from our API Definition.

/**
 * Result from the extract step in a pipeline. Inherits all core extraction fields and adds pipeline-specific timing.
 */
export interface PipelineExtractResult {
    /** Primary markdown content extracted from the document. Always present in the new format. */
    markdown?: string;
    /** Output from enabled extensions. Each key corresponds to an extension that was enabled in the request under `extensions.*`. Only keys for enabled extensions are present. */
    extensions?: PipelineExtractResult.Extensions;
    /** Positional bounding-box data for text, titles, headers, footers, images, and tables. Used by the frontend for annotation overlays. */
    bounding_boxes?: Record<string, unknown>;
    /** Persisted extraction ID. Present when storage is enabled (default). Use this ID with `/split` and `/schema` endpoints. */
    extraction_id?: string;
    /** URL to view the extraction on the Pulse platform. Present when storage is enabled. */
    extraction_url?: string;
    /** Number of pages processed. */
    page_count?: number;
    /** Billing tier and usage information. */
    plan_info?: PipelineExtractResult.PlanInfo;
    /** Non-fatal warnings generated during extraction. Includes deprecation notices when legacy input parameters are used, as well as processing warnings (e.g. word-level bounding box limitations). */
    warnings?: string[];
    /** Number of credits consumed by this request. Only present when the organization has the credit billing system enabled. */
    credits_used?: number | null;
    /** Number of pages processed. Convenience alias for `page_count`. */
    pages?: number;
    /** Step execution time in seconds. */
    latency?: number;
    /** Accepts any additional properties */
    [key: string]: any;
}

export namespace PipelineExtractResult {
    /**
     * Output from enabled extensions. Each key corresponds to an extension that was enabled in the request under `extensions.*`. Only keys for enabled extensions are present.
     */
    export interface Extensions {
        /** Chunk results by strategy. Present when `extensions.chunking` was provided in the request. */
        chunking?: Extensions.Chunking;
        /** List of detected footnotes with their in-text references. Present when `extensions.footnoteReferences` was enabled. Each item links a footnote paragraph to the body-text paragraphs that reference it, using bounding-box text IDs. */
        footnoteReferences?: Extensions.FootnoteReferences.Item[];
        /** Alternate output formats. Each key corresponds to an enabled alt output. */
        altOutputs?: Extensions.AltOutputs;
    }

    export namespace Extensions {
        /**
         * Chunk results by strategy. Present when `extensions.chunking` was provided in the request.
         */
        export interface Chunking {
            /** Semantically-segmented chunks. */
            semantic?: string[];
            /** Chunks split by document headers/headings. */
            header?: string[];
            /** One chunk per page. */
            page?: string[];
            /** Recursively-split chunks respecting size limits. */
            recursive?: string[];
        }

        export type FootnoteReferences = FootnoteReferences.Item[];

        export namespace FootnoteReferences {
            export interface Item {
                /** The footnote marker symbol (e.g. "*", "†", "1", "#"). */
                symbol?: string;
                /** The bounding-box text ID (e.g. "txt-15") of the footnote explanation paragraph. */
                footnoteTextId?: string;
                /** Bounding-box text IDs of body-text paragraphs that contain a reference to this footnote marker. */
                referenceTextIds?: string[];
            }
        }

        /**
         * Alternate output formats. Each key corresponds to an enabled alt output.
         */
        export interface AltOutputs {
            /** Word-level bounding box data. Present when `extensions.altOutputs.wlbb` was enabled and input is a PDF. */
            wlbb?: AltOutputs.Wlbb;
            /** HTML representation of the document. Present when `extensions.altOutputs.returnHtml` was enabled. */
            html?: string;
            /** XML representation of the document. Present when `extensions.altOutputs.returnXml` was enabled. (WIP) */
            xml?: string;
        }

        export namespace AltOutputs {
            /**
             * Word-level bounding box data. Present when `extensions.altOutputs.wlbb` was enabled and input is a PDF.
             */
            export interface Wlbb {
                /** List of detected words with their positions. */
                words?: Wlbb.Words.Item[];
                /** Error message if word-level extraction failed. */
                error?: string;
            }

            export namespace Wlbb {
                export type Words = Words.Item[];

                export namespace Words {
                    export interface Item {
                        /** Unique identifier for the word (e.g. "w-1", "w-2", …). */
                        id?: string;
                        /** The recognised word text. */
                        text?: string;
                        /** 1-indexed page number in the original document. */
                        page_number?: number;
                        /** Flat 4-corner polygon: [x1,y1, x2,y2, x3,y3, x4,y4]. All coordinates normalised to 0–1 range. */
                        bounding_box?: number[];
                        /** Recognition confidence score (0–1). */
                        average_word_confidence?: number;
                    }
                }
            }
        }
    }

    /**
     * Billing tier and usage information.
     */
    export interface PlanInfo {
        /** Current plan tier name. */
        tier?: string;
        /** Cumulative pages used after this extraction. */
        pages_used?: number;
        /** Human-readable plan note. */
        note?: string;
    }
}
