// This file was auto-generated by Fern from our API Definition.

import type * as Pulse from "../index.js";

/**
 * Result from the schema step in a pipeline.
 */
export interface PipelineSchemaResult {
    /** Persisted schema version ID. */
    schema_id?: string;
    /** Extracted values and citations. */
    schema_output?: Pulse.StructuredOutputResult;
    /** Step execution time in seconds. */
    latency?: number;
    /** Accepts any additional properties */
    [key: string]: any;
}
