// This file was auto-generated by Fern from our API Definition.

/**
 * Result from the batch_extract step in a pipeline.
 */
export interface PipelineBatchExtractResult {
    /** List of extraction IDs for each processed file. */
    extraction_ids?: string[];
    /** Number of files processed. */
    total_files?: number;
    /** Step execution time in seconds. */
    latency?: number;
    /** Accepts any additional properties */
    [key: string]: any;
}
