// This file was auto-generated by Fern from our API Definition.

import type * as Pulse from "../index.js";

/**
 * Ordered step definitions. Key order determines execution order. Use `extract` for single-file or `batch_extract` for multi-file pipelines — they are mutually exclusive. Each step accepts the same configuration as its standalone endpoint.
 */
export interface PipelineSteps {
    /** Single-document extraction step. Same options as `POST /extract`. */
    extract?: Pulse.ExtractOptions;
    /** Multi-document parallel extraction step. Provide `file_urls` at the top level and optional `workers` here. */
    batch_extract?: Pulse.PipelineStepBatchExtractConfig;
    /** Structured data extraction step. Same config as `schema_config` in `POST /schema`. Requires `extract` or `batch_extract` before it. */
    schema?: Pulse.SchemaConfig;
    /** Topic splitting step. Same config as `split_config` in `POST /split`. Requires `extract` or `batch_extract` before it. */
    split?: Pulse.SplitConfig;
    /** Table extraction step. Same config as `tables_config` in `POST /tables`. Requires `extract` before it. This is a terminal step — no further steps can follow. */
    tables?: Pulse.TablesConfig;
}
