// This file was auto-generated by Fern from our API Definition.

/**
 * Multipart form-data request body for ad-hoc pipeline execution. Upload file(s) directly and provide step configs as a JSON string.
 */
export interface PipelineExecuteMultipartInput {
    /** Document file to upload. For batch_extract, multiple `file` fields can be provided. */
    file?: string;
    /** JSON string containing the step configurations (same structure as `PipelineSteps`). */
    steps: string;
    /** Set to `"true"` for async execution. */
    async?: string;
    /** Set to `"true"` for zero-retention mode. */
    auto_delete?: string;
}
