// This file was auto-generated by Fern from our API Definition.

import type * as Pulse from "../index.js";

/**
 * Synchronous pipeline execution result. Contains the status, total latency, and results from each step.
 */
export interface PipelineExecuteResponse {
    /** Pipeline execution status. */
    status: PipelineExecuteResponse.Status;
    /** Total pipeline execution time in seconds. */
    total_latency?: number;
    /** Per-step results. */
    results: Pulse.PipelineResults;
    /** Present and true when auto-delete mode was used. Confirms that artifacts have been purged. */
    auto_delete?: boolean;
}

export namespace PipelineExecuteResponse {
    /** Pipeline execution status. */
    export const Status = {
        Completed: "completed",
    } as const;
    export type Status = (typeof Status)[keyof typeof Status];
}
