// This file was auto-generated by Fern from our API Definition.

/**
 * Inline schema configuration. Provide `input_schema` (JSON Schema) OR `excel_template` (base64 .xlsx) — not both. When `excel_template` is provided, the JSON Schema is auto-generated from the spreadsheet's column headers.
 */
export interface SchemaConfig {
    /** JSON Schema defining the structured data to extract. Required unless `excel_template` is provided. */
    input_schema?: Record<string, unknown>;
    /** Base64-encoded Excel template (.xlsx). When provided, the template's column headers are used to auto-generate the JSON Schema and a filled copy of the template is returned in the response as `excel_output_url`. Mutually exclusive with `input_schema`. */
    excel_template?: string;
    /** Natural language prompt with additional extraction instructions. */
    schema_prompt?: string;
    /** Enable extended reasoning for complex extractions. */
    effort?: boolean;
}
