// This file was auto-generated by Fern from our API Definition.

/**
 * Inline schema configuration.
 */
export interface SchemaConfig {
    /** JSON Schema defining the structured data to extract. */
    input_schema: Record<string, unknown>;
    /** Natural language prompt with additional extraction instructions. */
    schema_prompt?: string;
    /** Enable extended reasoning for complex extractions. */
    effort?: boolean;
}
