// This file was auto-generated by Fern from our API Definition.

import type * as Pulse from "../index.js";

/**
 * Response for single schema extraction mode.
 */
export interface SingleSchemaResponse {
    /** Unique identifier for this schema version. */
    schema_id: string;
    /** Version number of this schema for the extraction. */
    version: number;
    /** Extracted values and citations. */
    schema_output: Pulse.StructuredOutputResult;
    /** Present when multiple extractions were combined (via batch extract auto-detection or explicit `extraction_ids` input). Lists all source extraction IDs that contributed to the result. */
    extraction_ids?: string[];
    /** Number of credits consumed by this request. Only present when the organization has the credit billing system enabled. */
    credits_used?: number | null;
    /** Billing tier and cumulative usage information for the calling org, including this schema run. */
    plan_info?: Pulse.PlanInfo;
}
