// This file was auto-generated by Fern from our API Definition.

import type * as Pulse from "../index.js";

/**
 * Response for single schema extraction mode.
 */
export interface SingleSchemaResponse {
    /** Unique identifier for this schema version. */
    schema_id: string;
    /** Version number of this schema for the extraction. */
    version: number;
    /** Extracted values and citations. */
    schema_output: Pulse.StructuredOutputResult;
}
