// This file was auto-generated by Fern from our API Definition.

import type * as Pulse from "../index.js";

/**
 * Response for single schema extraction mode.
 */
export interface SingleSchemaResponse {
    /** Unique identifier for this schema version. */
    schema_id: string;
    /** Version number of this schema for the extraction. */
    version: number;
    /** Extracted values and citations. */
    schema_output: Pulse.StructuredOutputResult;
    /** Present when multiple extractions were combined (via batch extract auto-detection or explicit `extraction_ids` input). Lists all source extraction IDs that contributed to the result. */
    extraction_ids?: string[];
    /** API path to download the filled Excel template (e.g. `/schema/{schema_id}/excel`). Requires the same API key authentication. Only present when `excel_template` was provided in the request. */
    excel_output_url?: string;
}
