// This file was auto-generated by Fern from our API Definition.

/**
 * Page assignments per topic. Each key is a topic name and the value is an array of 1-indexed page numbers.
 */
export interface SplitOutput {
    /** Mapping of topic names to arrays of page numbers. */
    splits?: Record<string, number[]>;
}
