// This file was auto-generated by Fern from our API Definition.

import type * as Pulse from "../index.js";

/**
 * Core split result fields shared by the synchronous `/split` endpoint and the pipeline split step.
 */
export interface SplitResultCore {
    /** Unique identifier for this split result. Use this ID with the `/schema` endpoint (split mode) to apply schemas to specific page groups. */
    split_id?: string;
    /** Page assignments per topic. */
    split_output?: Pulse.SplitOutput;
    /** Number of credits consumed by this request. Only present when the organization has the credit billing system enabled. */
    credits_used?: number | null;
    /** Billing tier and cumulative usage information for the calling org, including this split run. */
    plan_info?: Pulse.PlanInfo;
}
