// This file was auto-generated by Fern from our API Definition.

import type * as Pulse from "../index.js";

/**
 * Response for split schema extraction mode.
 */
export interface SplitSchemaResponse {
    /** Unique identifier for this schema version. */
    schema_id: string;
    /** ID of the split that defined the page groups. */
    split_id: string;
    /** Per-topic extraction results. Keys match the topic names from the split. Each value contains `values` and `citations`. */
    results: Record<string, Pulse.StructuredOutputResult>;
    /** Echo of the schemas that were applied, keyed by topic. */
    input_schemas?: Record<string, Record<string, unknown>>;
    /** Per-topic errors if any topics failed to process. Keys are topic names, values are error messages. */
    errors?: Record<string, string>;
}
