// This file was auto-generated by Fern from our API Definition.

import type * as Pulse from "../index.js";

/**
 * Inline split configuration with topic definitions.
 */
export interface SplitConfig {
    /** List of topics to identify in the document. Each topic will be assigned page numbers where relevant content is found. */
    split_input: Pulse.TopicDefinition[];
}
