// This file was auto-generated by Fern from our API Definition.

import type * as Pulse from "../index.js";

/**
 * Result of document splitting with page assignments.
 */
export type SplitResponse = Pulse.SplitResultCore;
