// This file was auto-generated by Fern from our API Definition.

/**
 * Result of schema extraction with values and citations.
 */
export interface StructuredOutputResult {
    /** Extracted values matching the provided schema. */
    values?: Record<string, unknown>;
    /** Citation references linking extracted values to source locations. */
    citations?: Record<string, unknown>;
}
