// This file was auto-generated by Fern from our API Definition.

/**
 * Configuration for schema-guided extraction.
 */
export interface StructuredOutputConfig {
    /** JSON Schema defining the structured data to extract. */
    schema: Record<string, unknown>;
    /** Natural language instructions for extraction. */
    schemaPrompt?: string;
    /** Use higher quality model for better results. When true, uses a more capable model at the cost of higher latency. */
    effort?: boolean;
}
