// This file was auto-generated by Fern from our API Definition.

/**
 * Result of table extraction.
 */
export interface TablesResponse {
    /** Persisted tables version ID. Can be used to retrieve the tables result later. */
    tables_id: string;
    /** The extracted tables data. */
    tables_output: TablesResponse.TablesOutput;
}

export namespace TablesResponse {
    /**
     * The extracted tables data.
     */
    export interface TablesOutput {
        /** Array of extracted table objects. Each table includes its content, citations, and whether it was derived from a chart. */
        tables?: TablesOutput.Tables.Item[];
    }

    export namespace TablesOutput {
        export type Tables = Tables.Item[];

        export namespace Tables {
            export interface Item {
                /** The table content in the requested format (e.g. HTML). */
                table_content?: string;
                /** Bounding box table IDs indicating where this table was found (e.g. "tbl-1"). Merged tables list all source IDs. */
                citations?: string[];
                /** Whether this table was extracted from a chart or figure rather than a native table. */
                from_chart?: boolean;
            }
        }
    }
}
