// This file was auto-generated by Fern from our API Definition.

/**
 * Configuration for table extraction.
 */
export interface TablesConfig {
    /** When true, adjacent tables that appear to be continuations of each other are merged into a single table. */
    merge?: boolean;
    /** Output format for table content. Currently only `html` is supported. */
    table_format?: TablesConfig.TableFormat;
    /** Convert figures and charts into tables using LLM processing. Resulting tables have `from_chart: true` in the response. */
    charts_to_tables?: boolean;
}

export namespace TablesConfig {
    /** Output format for table content. Currently only `html` is supported. */
    export const TableFormat = {
        Html: "html",
    } as const;
    export type TableFormat = (typeof TableFormat)[keyof typeof TableFormat];
}
