// This file was auto-generated by Fern from our API Definition.

/**
 * Definition of a topic to identify in the document.
 */
export interface TopicDefinition {
    /** Unique identifier for the topic. Used as the key in the response and for referencing in subsequent schema extraction. */
    name: string;
    /** Optional description of what content belongs to this topic. Helps the AI identify relevant pages more accurately. */
    description?: string;
}
