// This file was auto-generated by Fern from our API Definition.

/**
 * Per-topic schema configuration.
 * Provide EITHER inline schema fields OR schema_config_id reference.
 */
export interface TopicSchemaConfig {
    /** JSON Schema for this topic. */
    schema?: Record<string, unknown>;
    /** Additional instructions for this topic. */
    schema_prompt?: string;
    /** Enable extended reasoning. */
    effort?: boolean;
    /** Reference to a saved schema configuration for this topic. */
    schema_config_id?: string;
}
