// This file was auto-generated by Fern from our API Definition.

/** Visual class of a bounding-box image. `chart` covers data visualizations (bar/line/pie etc., including spreadsheet chart objects). `image` covers non-chart embedded or detected visuals (logos, photos, screenshots). */
export const VisualType = {
    Chart: "chart",
    Image: "image",
} as const;
export type VisualType = (typeof VisualType)[keyof typeof VisualType];
