// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as Pulse from "../../../index.js";

export declare namespace WebhooksClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class WebhooksClient {
    protected readonly _options: NormalizedClientOptions<WebhooksClient.Options>;

    constructor(options: WebhooksClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * Generates a temporary link to the Svix webhook portal where users can manage their webhook endpoints and view message logs.
     *
     * @param {WebhooksClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Pulse.UnauthorizedError}
     * @throws {@link Pulse.InternalServerError}
     *
     * @example
     *     await client.webhooks.createWebhookLink()
     */
    public createWebhookLink(
        requestOptions?: WebhooksClient.RequestOptions,
    ): core.HttpResponsePromise<Pulse.CreateWebhookLinkResponse> {
        return core.HttpResponsePromise.fromPromise(this.__createWebhookLink(requestOptions));
    }

    private async __createWebhookLink(
        requestOptions?: WebhooksClient.RequestOptions,
    ): Promise<core.WithRawResponse<Pulse.CreateWebhookLinkResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PulseEnvironment.Default,
                "webhook",
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Pulse.CreateWebhookLinkResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 401:
                    throw new Pulse.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 500:
                    throw new Pulse.InternalServerError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PulseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/webhook");
    }
}
