// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         schemaId: "schemaId"
 *     }
 */
export interface DownloadSchemaExcelRequest {
    /** The schema ID returned from a prior `POST /schema` call. */
    schemaId: string;
}
