// This file was auto-generated by Fern from our API Definition.

import type * as core from "../../../core/index.js";

/**
 * @example
 *     {}
 */
export interface ExtractAsyncRequest {
    /** Document to upload directly. Required unless fileUrl is provided. */
    file?: core.file.Uploadable | undefined;
    /** Public or pre-signed URL that Pulse will download and extract. Required unless file is provided. */
    fileUrl?: string;
    /** **⚠️ DEPRECATED** — Use the `/schema` endpoint after extraction instead. Pass the `extraction_id` from the extract response to `/schema` with your `schema_config`. This parameter still works for backward compatibility but will be removed in a future version. */
    structuredOutput?: ExtractAsyncRequest.StructuredOutput;
    /** (Deprecated) JSON schema describing structured data to extract. Use structuredOutput instead. Accepts either a JSON object or a stringified JSON representation. */
    schema?: ExtractAsyncRequest.Schema;
    /** (Deprecated) Experimental schema definition used for feature flagged behaviour. Accepts either a JSON object or a stringified JSON representation. */
    experimentalSchema?: ExtractAsyncRequest.ExperimentalSchema;
    /** (Deprecated) Natural language prompt for schema-guided extraction. Use structuredOutput.schemaPrompt instead. */
    schemaPrompt?: string;
    /** (Deprecated) Custom instructions that augment the default extraction behaviour. */
    customPrompt?: string;
    /** Comma-separated list of chunking strategies to apply (for example `semantic,header,page,recursive`). */
    chunking?: string;
    /** Override for maximum characters per chunk when chunking is enabled. */
    chunkSize?: number;
    /** Page range filter supporting segments such as `1-2` or mixed ranges like `1-2,5`. */
    pages?: string;
    /** Toggle to enable figure extraction in results. */
    extractFigure?: boolean;
    /** Toggle to generate descriptive captions for extracted figures. */
    figureDescription?: boolean;
    /** Embed base64-encoded images inline in figure tags in the output. Increases response size. */
    showImages?: boolean;
    /** Whether to include HTML representation alongside markdown in the response. */
    returnHtml?: boolean;
    /** Enable extended reasoning mode for higher quality extraction on complex documents. Uses a more powerful model at higher latency. */
    effort?: boolean;
    /** (Deprecated) Enables expanded rationale output for debugging. */
    thinking?: boolean;
    /** Options for persisting extraction artifacts. When enabled (default), artifacts are saved to storage and a database record is created. */
    storage?: ExtractAsyncRequest.Storage;
    /** If true, returns immediately with a job_id for polling via GET /job/{jobId}. Otherwise processes synchronously. */
    async?: boolean;
}

export namespace ExtractAsyncRequest {
    /**
     * **⚠️ DEPRECATED** — Use the `/schema` endpoint after extraction instead. Pass the `extraction_id` from the extract response to `/schema` with your `schema_config`. This parameter still works for backward compatibility but will be removed in a future version.
     */
    export interface StructuredOutput {
        /** JSON schema describing the structured data to extract. */
        schema?: Record<string, unknown>;
        /** Natural language prompt with additional extraction instructions. */
        schemaPrompt?: string;
    }

    /**
     * (Deprecated) JSON schema describing structured data to extract. Use structuredOutput instead. Accepts either a JSON object or a stringified JSON representation.
     */
    export type Schema = Record<string, unknown> | string;
    /**
     * (Deprecated) Experimental schema definition used for feature flagged behaviour. Accepts either a JSON object or a stringified JSON representation.
     */
    export type ExperimentalSchema = Record<string, unknown> | string;

    /**
     * Options for persisting extraction artifacts. When enabled (default), artifacts are saved to storage and a database record is created.
     */
    export interface Storage {
        /** Whether to persist extraction artifacts. Set to false for temporary extractions with no storage or database record. */
        enabled?: boolean;
        /** Target folder name to save the extraction to. Creates the folder if it doesn't exist. */
        folderName?: string;
    }
}
