// This file was auto-generated by Fern from our API Definition.

import type * as Pulse from "../../index.js";

/**
 * @example
 *     {}
 */
export interface SchemaInput {
    /** ID of saved extraction to apply the schema to. Use for single-mode schema extraction. */
    extraction_id?: string;
    /** ID of saved split (from a prior `/split` call). Use for split-mode schema extraction. */
    split_id?: string;
    /** Inline schema configuration for single mode. Required (with extraction_id) if schema_config_id is not provided. */
    schema_config?: Pulse.SchemaConfig;
    /** Reference to a saved schema configuration for single mode. Use this instead of providing schema_config inline. */
    schema_config_id?: string;
    /** Per-topic schema configurations for split mode. Keys must match the topic names from the split. Each topic provides either inline schema or schema_config_id. */
    split_schema_config?: Record<string, Pulse.TopicSchemaConfig>;
    /** If true, returns immediately with a job_id for polling via  GET /job/{jobId}. Otherwise processes synchronously. */
    async?: boolean;
}
