// This file was auto-generated by Fern from our API Definition.

import type * as Pulse from "../../index.js";

/**
 * @example
 *     {
 *         extraction_id: "extraction_id"
 *     }
 */
export interface SplitInput {
    /** ID of the saved extraction to split. */
    extraction_id: string;
    /** Inline split configuration with topics. Required if split_config_id is not provided. */
    split_config?: Pulse.SplitConfig;
    /** Reference to a saved split configuration. Use this instead of providing split_config inline. */
    split_config_id?: string;
    /** If true, returns immediately with a job_id for polling via  GET /job/{jobId}. Otherwise processes synchronously. */
    async?: boolean;
}
