// This file was auto-generated by Fern from our API Definition.

import type * as Pulse from "../../index.js";

/**
 * @example
 *     {
 *         extraction_id: "extraction_id"
 *     }
 */
export interface TablesInput {
    /** ID of a completed extraction to extract tables from. */
    extraction_id: string;
    /** Table extraction configuration. If omitted, defaults are used (`merge: false`, `table_format: "html"`). */
    tables_config?: Pulse.TablesConfig;
    /** When true, returns immediately with a job ID. Poll `GET /job/{tables_id}` for the result. */
    async?: boolean;
}
