// This file was auto-generated by Fern from our API Definition.

import type * as Pulse from "../../../../index.js";

/**
 * @example
 *     {
 *         input: {},
 *         output: {}
 *     }
 */
export interface BatchExtractInput {
    /** Source of files to process. */
    input: Pulse.BatchInputSource;
    /** Where to save extraction result JSON files. */
    output: Pulse.BatchOutputDestination;
    /** Options forwarded to each `/extract` call (e.g. `pages`, `figureProcessing`, `extensions`). */
    extract_options?: Record<string, unknown>;
    /** Number of parallel workers. Higher values increase throughput but consume more server resources. */
    workers?: number;
}
