// This file was auto-generated by Fern from our API Definition.

import type * as Pulse from "../../../../index.js";

/**
 * @example
 *     {
 *         output: {},
 *         split_config: {
 *             split_input: [{
 *                     name: "name"
 *                 }]
 *         }
 *     }
 */
export interface BatchSplitInput {
    /** ID of a prior `/batch/extract` run. All completed child extraction IDs will be used. */
    batch_extract_id?: string;
    /** Explicit list of extraction IDs to process. */
    extraction_ids?: string[];
    /** Where to save split result JSON files. */
    output: Pulse.BatchOutputDestination;
    /** Split configuration with topic definitions. Applied to each extraction. */
    split_config: Pulse.SplitConfig;
    /** Number of parallel workers. */
    workers?: number;
}
