// This file was auto-generated by Fern from our API Definition.

import type * as Pulse from "../../../../index.js";

/**
 * @example
 *     {
 *         output: {}
 *     }
 */
export interface BatchTablesInput {
    /** ID of a prior `/batch/extract` run. All completed child extraction IDs will be used. */
    batch_extract_id?: string;
    /** Explicit list of extraction IDs to process. */
    extraction_ids?: string[];
    /** Where to save table result JSON files. */
    output: Pulse.BatchOutputDestination;
    /** Table extraction configuration forwarded to each `/tables` call. */
    tables_config?: Pulse.TablesConfig;
    /** Number of parallel workers. */
    workers?: number;
}
