// This file was auto-generated by Fern from our API Definition.

import * as Pulse from "../../src/api/index";
import { PulseClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("BatchClient", () => {
    test("extract (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { input: {}, output: {} };
        const rawResponseBody = { batch_job_id: "batch_job_id", status: "processing", total_files: 1 };
        server
            .mockEndpoint()
            .post("/batch/extract")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.batch.extract({
            input: {},
            output: {},
        });
        expect(response).toEqual({
            batch_job_id: "batch_job_id",
            status: "processing",
            total_files: 1,
        });
    });

    test("extract (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { input: {}, output: {} };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/batch/extract")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.batch.extract({
                input: {},
                output: {},
            });
        }).rejects.toThrow(Pulse.BadRequestError);
    });

    test("extract (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { input: {}, output: {} };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/batch/extract")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.batch.extract({
                input: {},
                output: {},
            });
        }).rejects.toThrow(Pulse.UnauthorizedError);
    });

    test("extract (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { input: {}, output: {} };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/batch/extract")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.batch.extract({
                input: {},
                output: {},
            });
        }).rejects.toThrow(Pulse.TooManyRequestsError);
    });

    test("schema (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { output: {} };
        const rawResponseBody = {
            batch_job_id: "batch_job_id",
            status: "processing",
            total_extractions: 1,
            total_splits: 1,
        };
        server
            .mockEndpoint()
            .post("/batch/schema")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.batch.schema({
            output: {},
        });
        expect(response).toEqual({
            batch_job_id: "batch_job_id",
            status: "processing",
            total_extractions: 1,
            total_splits: 1,
        });
    });

    test("schema (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { output: {} };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/batch/schema")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.batch.schema({
                output: {},
            });
        }).rejects.toThrow(Pulse.BadRequestError);
    });

    test("schema (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { output: {} };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/batch/schema")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.batch.schema({
                output: {},
            });
        }).rejects.toThrow(Pulse.UnauthorizedError);
    });

    test("schema (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { output: {} };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/batch/schema")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.batch.schema({
                output: {},
            });
        }).rejects.toThrow(Pulse.NotFoundError);
    });

    test("schema (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { output: {} };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/batch/schema")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.batch.schema({
                output: {},
            });
        }).rejects.toThrow(Pulse.TooManyRequestsError);
    });

    test("tables (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { output: {} };
        const rawResponseBody = { batch_job_id: "batch_job_id", status: "processing", total_extractions: 1 };
        server
            .mockEndpoint()
            .post("/batch/tables")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.batch.tables({
            output: {},
        });
        expect(response).toEqual({
            batch_job_id: "batch_job_id",
            status: "processing",
            total_extractions: 1,
        });
    });

    test("tables (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { output: {} };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/batch/tables")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.batch.tables({
                output: {},
            });
        }).rejects.toThrow(Pulse.BadRequestError);
    });

    test("tables (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { output: {} };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/batch/tables")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.batch.tables({
                output: {},
            });
        }).rejects.toThrow(Pulse.UnauthorizedError);
    });

    test("tables (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { output: {} };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/batch/tables")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.batch.tables({
                output: {},
            });
        }).rejects.toThrow(Pulse.NotFoundError);
    });

    test("tables (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { output: {} };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/batch/tables")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.batch.tables({
                output: {},
            });
        }).rejects.toThrow(Pulse.TooManyRequestsError);
    });

    test("split (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { output: {}, split_config: { split_input: [{ name: "name" }] } };
        const rawResponseBody = { batch_job_id: "batch_job_id", status: "processing", total_extractions: 1 };
        server
            .mockEndpoint()
            .post("/batch/split")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.batch.split({
            output: {},
            split_config: {
                split_input: [
                    {
                        name: "name",
                    },
                ],
            },
        });
        expect(response).toEqual({
            batch_job_id: "batch_job_id",
            status: "processing",
            total_extractions: 1,
        });
    });

    test("split (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { output: {}, split_config: { split_input: [{ name: "name" }, { name: "name" }] } };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/batch/split")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.batch.split({
                output: {},
                split_config: {
                    split_input: [
                        {
                            name: "name",
                        },
                        {
                            name: "name",
                        },
                    ],
                },
            });
        }).rejects.toThrow(Pulse.BadRequestError);
    });

    test("split (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { output: {}, split_config: { split_input: [{ name: "name" }, { name: "name" }] } };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/batch/split")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.batch.split({
                output: {},
                split_config: {
                    split_input: [
                        {
                            name: "name",
                        },
                        {
                            name: "name",
                        },
                    ],
                },
            });
        }).rejects.toThrow(Pulse.UnauthorizedError);
    });

    test("split (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { output: {}, split_config: { split_input: [{ name: "name" }, { name: "name" }] } };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/batch/split")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.batch.split({
                output: {},
                split_config: {
                    split_input: [
                        {
                            name: "name",
                        },
                        {
                            name: "name",
                        },
                    ],
                },
            });
        }).rejects.toThrow(Pulse.NotFoundError);
    });

    test("split (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { output: {}, split_config: { split_input: [{ name: "name" }, { name: "name" }] } };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/batch/split")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.batch.split({
                output: {},
                split_config: {
                    split_input: [
                        {
                            name: "name",
                        },
                        {
                            name: "name",
                        },
                    ],
                },
            });
        }).rejects.toThrow(Pulse.TooManyRequestsError);
    });
});
