// This file was auto-generated by Fern from our API Definition.

import * as Pulse from "../../src/api/index";
import { PulseClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("FormClient", () => {
    test("detect (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            form_id: "form_id",
            page_count: 1,
            pdf_url: "pdf_url",
            form_fields: [
                {
                    page_number: 1,
                    bounding_box: [1.1],
                    text: "text",
                    type: "text",
                    row: 1,
                    col: 1,
                    table_idx: 1,
                    checkbox_details: [{}],
                },
            ],
            fields_filled: 1,
            fields_cleared: 1,
            credits_used: 1.1,
            plan_info: { tier: "tier", total_credits_used: 1.1, pages_used: 1 },
        };
        server
            .mockEndpoint()
            .post("/form/detect")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.form.detect();
        expect(response).toEqual({
            form_id: "form_id",
            page_count: 1,
            pdf_url: "pdf_url",
            form_fields: [
                {
                    page_number: 1,
                    bounding_box: [1.1],
                    text: "text",
                    type: "text",
                    row: 1,
                    col: 1,
                    table_idx: 1,
                    checkbox_details: [{}],
                },
            ],
            fields_filled: 1,
            fields_cleared: 1,
            credits_used: 1.1,
            plan_info: {
                tier: "tier",
                total_credits_used: 1.1,
                pages_used: 1,
            },
        });
    });

    test("detect (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/form/detect")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.form.detect();
        }).rejects.toThrow(Pulse.BadRequestError);
    });

    test("detect (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/form/detect")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.form.detect();
        }).rejects.toThrow(Pulse.UnauthorizedError);
    });

    test("detect (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/form/detect")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.form.detect();
        }).rejects.toThrow(Pulse.ForbiddenError);
    });

    test("detect (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/form/detect")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.form.detect();
        }).rejects.toThrow(Pulse.NotFoundError);
    });

    test("detect (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/form/detect")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.form.detect();
        }).rejects.toThrow(Pulse.TooManyRequestsError);
    });

    test("detect (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/form/detect")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.form.detect();
        }).rejects.toThrow(Pulse.InternalServerError);
    });

    test("fill (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { instructions: "instructions" };
        const rawResponseBody = {
            form_id: "form_id",
            page_count: 1,
            pdf_url: "pdf_url",
            form_fields: [
                {
                    page_number: 1,
                    bounding_box: [1.1],
                    text: "text",
                    type: "text",
                    row: 1,
                    col: 1,
                    table_idx: 1,
                    checkbox_details: [{}],
                },
            ],
            fields_filled: 1,
            fields_cleared: 1,
            credits_used: 1.1,
            plan_info: { tier: "tier", total_credits_used: 1.1, pages_used: 1 },
        };
        server
            .mockEndpoint()
            .post("/form/fill")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.form.fill({
            instructions: "instructions",
        });
        expect(response).toEqual({
            form_id: "form_id",
            page_count: 1,
            pdf_url: "pdf_url",
            form_fields: [
                {
                    page_number: 1,
                    bounding_box: [1.1],
                    text: "text",
                    type: "text",
                    row: 1,
                    col: 1,
                    table_idx: 1,
                    checkbox_details: [{}],
                },
            ],
            fields_filled: 1,
            fields_cleared: 1,
            credits_used: 1.1,
            plan_info: {
                tier: "tier",
                total_credits_used: 1.1,
                pages_used: 1,
            },
        });
    });

    test("fill (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { instructions: "instructions" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/form/fill")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.form.fill({
                instructions: "instructions",
            });
        }).rejects.toThrow(Pulse.BadRequestError);
    });

    test("fill (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { instructions: "instructions" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/form/fill")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.form.fill({
                instructions: "instructions",
            });
        }).rejects.toThrow(Pulse.UnauthorizedError);
    });

    test("fill (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { instructions: "instructions" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/form/fill")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.form.fill({
                instructions: "instructions",
            });
        }).rejects.toThrow(Pulse.ForbiddenError);
    });

    test("fill (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { instructions: "instructions" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/form/fill")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.form.fill({
                instructions: "instructions",
            });
        }).rejects.toThrow(Pulse.NotFoundError);
    });

    test("fill (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { instructions: "instructions" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/form/fill")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.form.fill({
                instructions: "instructions",
            });
        }).rejects.toThrow(Pulse.TooManyRequestsError);
    });

    test("fill (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { instructions: "instructions" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/form/fill")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.form.fill({
                instructions: "instructions",
            });
        }).rejects.toThrow(Pulse.InternalServerError);
    });

    test("clear (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            form_id: "form_id",
            page_count: 1,
            pdf_url: "pdf_url",
            form_fields: [
                {
                    page_number: 1,
                    bounding_box: [1.1],
                    text: "text",
                    type: "text",
                    row: 1,
                    col: 1,
                    table_idx: 1,
                    checkbox_details: [{}],
                },
            ],
            fields_filled: 1,
            fields_cleared: 1,
            credits_used: 1.1,
            plan_info: { tier: "tier", total_credits_used: 1.1, pages_used: 1 },
        };
        server
            .mockEndpoint()
            .post("/form/clear")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.form.clear();
        expect(response).toEqual({
            form_id: "form_id",
            page_count: 1,
            pdf_url: "pdf_url",
            form_fields: [
                {
                    page_number: 1,
                    bounding_box: [1.1],
                    text: "text",
                    type: "text",
                    row: 1,
                    col: 1,
                    table_idx: 1,
                    checkbox_details: [{}],
                },
            ],
            fields_filled: 1,
            fields_cleared: 1,
            credits_used: 1.1,
            plan_info: {
                tier: "tier",
                total_credits_used: 1.1,
                pages_used: 1,
            },
        });
    });

    test("clear (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/form/clear")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.form.clear();
        }).rejects.toThrow(Pulse.BadRequestError);
    });

    test("clear (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/form/clear")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.form.clear();
        }).rejects.toThrow(Pulse.UnauthorizedError);
    });

    test("clear (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/form/clear")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.form.clear();
        }).rejects.toThrow(Pulse.ForbiddenError);
    });

    test("clear (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/form/clear")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.form.clear();
        }).rejects.toThrow(Pulse.NotFoundError);
    });

    test("clear (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/form/clear")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.form.clear();
        }).rejects.toThrow(Pulse.TooManyRequestsError);
    });

    test("clear (7)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/form/clear")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.form.clear();
        }).rejects.toThrow(Pulse.InternalServerError);
    });
});
