// This file was auto-generated by Fern from our API Definition.

import * as Pulse from "../../src/api/index";
import { PulseClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("JobsClient", () => {
    test("getJob (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = {
            job_id: "job_id",
            status: "pending",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            result: { key: "value" },
            error: "error",
        };
        server.mockEndpoint().get("/job/jobId").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.jobs.getJob({
            jobId: "jobId",
        });
        expect(response).toEqual({
            job_id: "job_id",
            status: "pending",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
            result: {
                key: "value",
            },
            error: "error",
        });
    });

    test("getJob (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/job/jobId").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.getJob({
                jobId: "jobId",
            });
        }).rejects.toThrow(Pulse.UnauthorizedError);
    });

    test("getJob (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/job/jobId").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.getJob({
                jobId: "jobId",
            });
        }).rejects.toThrow(Pulse.ForbiddenError);
    });

    test("getJob (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/job/jobId").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.getJob({
                jobId: "jobId",
            });
        }).rejects.toThrow(Pulse.NotFoundError);
    });

    test("getJob (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/job/jobId").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.getJob({
                jobId: "jobId",
            });
        }).rejects.toThrow(Pulse.TooManyRequestsError);
    });

    test("getJob (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/job/jobId").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.getJob({
                jobId: "jobId",
            });
        }).rejects.toThrow(Pulse.InternalServerError);
    });

    test("cancelJob (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { job_id: "job_id", message: "message" };
        server.mockEndpoint().delete("/job/jobId").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.jobs.cancelJob({
            jobId: "jobId",
        });
        expect(response).toEqual({
            job_id: "job_id",
            message: "message",
        });
    });

    test("cancelJob (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().delete("/job/jobId").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.cancelJob({
                jobId: "jobId",
            });
        }).rejects.toThrow(Pulse.UnauthorizedError);
    });

    test("cancelJob (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().delete("/job/jobId").respondWith().statusCode(403).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.cancelJob({
                jobId: "jobId",
            });
        }).rejects.toThrow(Pulse.ForbiddenError);
    });

    test("cancelJob (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().delete("/job/jobId").respondWith().statusCode(404).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.cancelJob({
                jobId: "jobId",
            });
        }).rejects.toThrow(Pulse.NotFoundError);
    });

    test("cancelJob (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().delete("/job/jobId").respondWith().statusCode(429).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.cancelJob({
                jobId: "jobId",
            });
        }).rejects.toThrow(Pulse.TooManyRequestsError);
    });

    test("cancelJob (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().delete("/job/jobId").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.jobs.cancelJob({
                jobId: "jobId",
            });
        }).rejects.toThrow(Pulse.InternalServerError);
    });
});
