// This file was auto-generated by Fern from our API Definition.

import * as Pulse from "../../src/api/index";
import { PulseClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("LargeResultsClient", () => {
    test("getLargeResult (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {
            markdown: "markdown",
            extensions: {
                chunking: { semantic: ["semantic"], header: ["header"], page: ["page"], recursive: ["recursive"] },
                footnoteReferences: [{}],
                altOutputs: { html: "html", xml: "xml" },
            },
            bounding_boxes: { key: "value" },
            extraction_id: "extraction_id",
            extraction_url: "extraction_url",
            page_count: 1,
            plan_info: { tier: "tier", pages_used: 1, note: "note" },
            warnings: ["warnings"],
            credits_used: 1.1,
        };
        server
            .mockEndpoint()
            .get("/large_results/jobId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.largeResults.getLargeResult({
            jobId: "jobId",
        });
        expect(response).toEqual({
            markdown: "markdown",
            extensions: {
                chunking: {
                    semantic: ["semantic"],
                    header: ["header"],
                    page: ["page"],
                    recursive: ["recursive"],
                },
                footnoteReferences: [{}],
                altOutputs: {
                    html: "html",
                    xml: "xml",
                },
            },
            bounding_boxes: {
                key: "value",
            },
            extraction_id: "extraction_id",
            extraction_url: "extraction_url",
            page_count: 1,
            plan_info: {
                tier: "tier",
                pages_used: 1,
                note: "note",
            },
            warnings: ["warnings"],
            credits_used: 1.1,
        });
    });

    test("getLargeResult (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/large_results/jobId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.largeResults.getLargeResult({
                jobId: "jobId",
            });
        }).rejects.toThrow(Pulse.NotFoundError);
    });

    test("getLargeResult (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = {};
        server
            .mockEndpoint()
            .get("/large_results/jobId")
            .respondWith()
            .statusCode(410)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.largeResults.getLargeResult({
                jobId: "jobId",
            });
        }).rejects.toThrow(Pulse.GoneError);
    });

    test("getLargeResult (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/large_results/jobId")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.largeResults.getLargeResult({
                jobId: "jobId",
            });
        }).rejects.toThrow(Pulse.InternalServerError);
    });
});
