// This file was auto-generated by Fern from our API Definition.

import * as Pulse from "../../src/api/index";
import { PulseClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("PulseClient", () => {
    test("split (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { extraction_id: "extraction_id" };
        const rawResponseBody = { split_id: "split_id", split_output: { splits: { key: [1] } } };
        server
            .mockEndpoint()
            .post("/split")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.split({
            extraction_id: "extraction_id",
        });
        expect(response).toEqual({
            split_id: "split_id",
            split_output: {
                splits: {
                    key: [1],
                },
            },
        });
    });

    test("split (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { extraction_id: "extraction_id" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/split")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.split({
                extraction_id: "extraction_id",
            });
        }).rejects.toThrow(Pulse.BadRequestError);
    });

    test("split (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { extraction_id: "extraction_id" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/split")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.split({
                extraction_id: "extraction_id",
            });
        }).rejects.toThrow(Pulse.UnauthorizedError);
    });

    test("split (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { extraction_id: "extraction_id" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/split")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.split({
                extraction_id: "extraction_id",
            });
        }).rejects.toThrow(Pulse.NotFoundError);
    });

    test("split (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { extraction_id: "extraction_id" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/split")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.split({
                extraction_id: "extraction_id",
            });
        }).rejects.toThrow(Pulse.TooManyRequestsError);
    });

    test("split (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { extraction_id: "extraction_id" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/split")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.split({
                extraction_id: "extraction_id",
            });
        }).rejects.toThrow(Pulse.InternalServerError);
    });

    test("schema (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {
            schema_id: "schema_id",
            version: 1,
            schema_output: { values: { key: "value" }, citations: { key: "value" } },
        };
        server
            .mockEndpoint()
            .post("/schema")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.schema();
        expect(response).toEqual({
            schema_id: "schema_id",
            version: 1,
            schema_output: {
                values: {
                    key: "value",
                },
                citations: {
                    key: "value",
                },
            },
        });
    });

    test("schema (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/schema")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.schema();
        }).rejects.toThrow(Pulse.BadRequestError);
    });

    test("schema (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/schema")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.schema();
        }).rejects.toThrow(Pulse.UnauthorizedError);
    });

    test("schema (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/schema")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.schema();
        }).rejects.toThrow(Pulse.NotFoundError);
    });

    test("schema (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/schema")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.schema();
        }).rejects.toThrow(Pulse.TooManyRequestsError);
    });

    test("schema (6)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/schema")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.schema();
        }).rejects.toThrow(Pulse.InternalServerError);
    });
});
