// This file was auto-generated by Fern from our API Definition.

import * as Pulse from "../../src/api/index";
import { PulseClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("PulseClient", () => {
    test("extract (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { fileUrl: "fileUrl" };
        const rawResponseBody = {
            content: "content",
            html: "html",
            job_id: "job_id",
            warnings: ["warnings"],
            metadata: { key: "value" },
        };
        server
            .mockEndpoint()
            .post("/extract")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.extract({
            fileUrl: "fileUrl",
        });
        expect(response).toEqual({
            content: "content",
            html: "html",
            job_id: "job_id",
            warnings: ["warnings"],
            metadata: {
                key: "value",
            },
        });
    });

    test("extract (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { fileUrl: "fileUrl" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/extract")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.extract({
                fileUrl: "fileUrl",
            });
        }).rejects.toThrow(Pulse.BadRequestError);
    });

    test("extract (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { fileUrl: "fileUrl" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/extract")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.extract({
                fileUrl: "fileUrl",
            });
        }).rejects.toThrow(Pulse.UnauthorizedError);
    });

    test("extract (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { fileUrl: "fileUrl" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/extract")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.extract({
                fileUrl: "fileUrl",
            });
        }).rejects.toThrow(Pulse.TooManyRequestsError);
    });

    test("extractAsync (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { fileUrl: "fileUrl" };
        const rawResponseBody = { job_id: "job_id", status: "pending", queuedAt: "2024-01-15T09:30:00Z" };
        server
            .mockEndpoint()
            .post("/extract_async")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.extractAsync({
            fileUrl: "fileUrl",
        });
        expect(response).toEqual({
            job_id: "job_id",
            status: "pending",
            queuedAt: "2024-01-15T09:30:00Z",
        });
    });

    test("extractAsync (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { fileUrl: "fileUrl" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/extract_async")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.extractAsync({
                fileUrl: "fileUrl",
            });
        }).rejects.toThrow(Pulse.BadRequestError);
    });

    test("extractAsync (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { fileUrl: "fileUrl" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/extract_async")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.extractAsync({
                fileUrl: "fileUrl",
            });
        }).rejects.toThrow(Pulse.UnauthorizedError);
    });

    test("extractAsync (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { fileUrl: "fileUrl" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/extract_async")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.extractAsync({
                fileUrl: "fileUrl",
            });
        }).rejects.toThrow(Pulse.TooManyRequestsError);
    });
});
