// This file was auto-generated by Fern from our API Definition.

import * as Pulse from "../../src/api/index";
import { PulseClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("PipelineClient", () => {
    test("execute (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { steps: {} };
        const rawResponseBody = {
            status: "completed",
            total_latency: 1.1,
            results: {
                extract: {
                    markdown: "markdown",
                    extraction_id: "extraction_id",
                    extraction_url: "extraction_url",
                    page_count: 1,
                    warnings: ["warnings"],
                    credits_used: 1.1,
                    pages: 1,
                    latency: 1.1,
                },
                batch_extract: { extraction_ids: ["extraction_ids"], total_files: 1, latency: 1.1 },
                schema: { schema_id: "schema_id", latency: 1.1 },
                split: { split_id: "split_id", credits_used: 1.1, split_input: [{ name: "name" }], latency: 1.1 },
                tables: { tables_id: "tables_id", latency: 1.1 },
            },
            auto_delete: true,
        };
        server
            .mockEndpoint()
            .post("/pipeline/execute")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.pipeline.execute({
            steps: {},
        });
        expect(response).toEqual({
            status: "completed",
            total_latency: 1.1,
            results: {
                extract: {
                    markdown: "markdown",
                    extraction_id: "extraction_id",
                    extraction_url: "extraction_url",
                    page_count: 1,
                    warnings: ["warnings"],
                    credits_used: 1.1,
                    pages: 1,
                    latency: 1.1,
                },
                batch_extract: {
                    extraction_ids: ["extraction_ids"],
                    total_files: 1,
                    latency: 1.1,
                },
                schema: {
                    schema_id: "schema_id",
                    latency: 1.1,
                },
                split: {
                    split_id: "split_id",
                    credits_used: 1.1,
                    split_input: [
                        {
                            name: "name",
                        },
                    ],
                    latency: 1.1,
                },
                tables: {
                    tables_id: "tables_id",
                    latency: 1.1,
                },
            },
            auto_delete: true,
        });
    });

    test("execute (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { steps: {} };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/pipeline/execute")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.pipeline.execute({
                steps: {},
            });
        }).rejects.toThrow(Pulse.BadRequestError);
    });

    test("execute (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { steps: {} };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/pipeline/execute")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.pipeline.execute({
                steps: {},
            });
        }).rejects.toThrow(Pulse.UnauthorizedError);
    });

    test("execute (4)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { steps: {} };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/pipeline/execute")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.pipeline.execute({
                steps: {},
            });
        }).rejects.toThrow(Pulse.ForbiddenError);
    });

    test("execute (5)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });
        const rawRequestBody = { steps: {} };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/pipeline/execute")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.pipeline.execute({
                steps: {},
            });
        }).rejects.toThrow(Pulse.TooManyRequestsError);
    });
});
