// This file was auto-generated by Fern from our API Definition.

import * as Pulse from "../../src/api/index";
import { PulseClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("WebhooksClient", () => {
    test("createWebhookLink (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { link: "link" };
        server.mockEndpoint().post("/webhook").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.webhooks.createWebhookLink();
        expect(response).toEqual({
            link: "link",
        });
    });

    test("createWebhookLink (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().post("/webhook").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.createWebhookLink();
        }).rejects.toThrow(Pulse.UnauthorizedError);
    });

    test("createWebhookLink (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new PulseClient({ maxRetries: 0, apiKey: "test", environment: server.baseUrl });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().post("/webhook").respondWith().statusCode(500).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.webhooks.createWebhookLink();
        }).rejects.toThrow(Pulse.InternalServerError);
    });
});
