// This file was auto-generated by Fern from our API Definition.

import * as Pulse from "./api/index.js";
import { JobsClient } from "./api/resources/jobs/client/Client.js";
import { WebhooksClient } from "./api/resources/webhooks/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "./BaseClient.js";
import { mergeHeaders } from "./core/headers.js";
import * as core from "./core/index.js";
import * as environments from "./environments.js";
import { handleNonStatusCodeError } from "./errors/handleNonStatusCodeError.js";
import * as errors from "./errors/index.js";

export declare namespace PulseClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class PulseClient {
    protected readonly _options: NormalizedClientOptions<PulseClient.Options>;
    protected _jobs: JobsClient | undefined;
    protected _webhooks: WebhooksClient | undefined;

    constructor(options: PulseClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    public get jobs(): JobsClient {
        return (this._jobs ??= new JobsClient(this._options));
    }

    public get webhooks(): WebhooksClient {
        return (this._webhooks ??= new WebhooksClient(this._options));
    }

    /**
     * The primary endpoint for the Pulse API. Parses uploaded documents or remote
     * file URLs and returns rich markdown content with optional structured data
     * extraction based on user-provided schemas and extraction options.
     *
     * @param {Pulse.ExtractJsonInput} request
     * @param {PulseClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Pulse.BadRequestError}
     * @throws {@link Pulse.UnauthorizedError}
     * @throws {@link Pulse.TooManyRequestsError}
     *
     * @example
     *     await client.extract({
     *         fileUrl: "fileUrl"
     *     })
     */
    public extract(
        request: Pulse.ExtractJsonInput,
        requestOptions?: PulseClient.RequestOptions,
    ): core.HttpResponsePromise<Pulse.ExtractResponse> {
        return core.HttpResponsePromise.fromPromise(this.__extract(request, requestOptions));
    }

    private async __extract(
        request: Pulse.ExtractJsonInput,
        requestOptions?: PulseClient.RequestOptions,
    ): Promise<core.WithRawResponse<Pulse.ExtractResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PulseEnvironment.Default,
                "extract",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Pulse.ExtractResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Pulse.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Pulse.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Pulse.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PulseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/extract");
    }

    /**
     * Starts an asynchronous extraction job. The request mirrors the
     * synchronous options but returns immediately with a job identifier that
     * clients can poll for completion status.
     *
     * @param {Pulse.ExtractJsonInput} request
     * @param {PulseClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Pulse.BadRequestError}
     * @throws {@link Pulse.UnauthorizedError}
     * @throws {@link Pulse.TooManyRequestsError}
     *
     * @example
     *     await client.extractAsync({
     *         fileUrl: "fileUrl"
     *     })
     */
    public extractAsync(
        request: Pulse.ExtractJsonInput,
        requestOptions?: PulseClient.RequestOptions,
    ): core.HttpResponsePromise<Pulse.ExtractAsyncResponse> {
        return core.HttpResponsePromise.fromPromise(this.__extractAsync(request, requestOptions));
    }

    private async __extractAsync(
        request: Pulse.ExtractJsonInput,
        requestOptions?: PulseClient.RequestOptions,
    ): Promise<core.WithRawResponse<Pulse.ExtractAsyncResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PulseEnvironment.Default,
                "extract_async",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body as Pulse.ExtractAsyncResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 400:
                    throw new Pulse.BadRequestError(_response.error.body as unknown, _response.rawResponse);
                case 401:
                    throw new Pulse.UnauthorizedError(_response.error.body as unknown, _response.rawResponse);
                case 429:
                    throw new Pulse.TooManyRequestsError(_response.error.body as unknown, _response.rawResponse);
                default:
                    throw new errors.PulseError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/extract_async");
    }
}
