// This file was auto-generated by Fern from our API Definition.

export const PulseEnvironment = {
    Default: "https://api.pulse.dev",
} as const;

export type PulseEnvironment = typeof PulseEnvironment.Default;
